export const data = {
  nodes: [
    {id: 1, type: 'web', name: '1-氯-2,3-环氧丙烷', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 2, type: 'web', name: '1,2-环氧丙烷', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 3, type: 'web', name: '3-氨基丙烯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 4, type: 'web', name: '一氧化碳', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 5, type: 'web', name: '一氯甲烷', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 6, type: 'web', name: '一甲胺', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 7, type: 'web', name: '丁二烯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 8, type: 'web', name: '三氟化硼', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 9, type: 'web', name: '三氯甲烷', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 10, type: 'web', name: '丙烯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 11, type: 'web', name: '丙烯腈', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 12, type: 'web', name: '丙烯酸', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 13, type: 'web', name: '丙烯酸[稳定的]', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 14, type: 'web', name: '丙酮', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 15, type: 'web', name: '乙炔', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 16, type: 'web', name: '乙烯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 17, type: 'web', name: '乙酸乙酯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 18, type: 'web', name: '乙醛', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 19, type: 'web', name: '四氯化钛', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 20, type: 'web', name: '无水甲醛，含水量低于0.01%', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 21, type: 'web', name: '氟化氢[无水]', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 22, type: 'web', name: '氢', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 23, type: 'web', name: '氢氟酸', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 24, type: 'web', name: '氢氧化钾', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 25, type: 'web', name: '氨', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 26, type: 'web', name: '氯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 27, type: 'web', name: '氯甲基甲醚', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 28, type: 'web', name: '氯苯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 29, type: 'web', name: '氯酸钠', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 30, type: 'web', name: '氰化钠', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 31, type: 'web', name: '汽油', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 32, type: 'web', name: '液化石油气', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 33, type: 'web', name: '液氨', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 34, type: 'web', name: '环氧丙烷', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 35, type: 'web', name: '环氧乙烷', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 36, type: 'web', name: '环氧氯丙烷', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 37, type: 'web', name: '甲基叔丁基醚', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 38, type: 'web', name: '甲基肼', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 39, type: 'web', name: '甲烷', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 40, type: 'web', name: '甲苯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 41, type: 'web', name: '甲苯-2,4-二异氰酸酯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 42, type: 'web', name: '甲苯二异氰酸酯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 43, type: 'web', name: '甲醇', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 44, type: 'web', name: '石脑油', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 45, type: 'web', name: '硝酸胍', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 46, type: 'web', name: '硫酸', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 47, type: 'web', name: '硫酸二甲酯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 48, type: 'web', name: '磷化氢', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 49, type: 'web', name: '苯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 50, type: 'web', name: '苯乙烯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 51, type: 'web', name: '苯乙烯[稳定的]', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 52, type: 'web', name: '苯胺', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 53, type: 'web', name: '苯酚', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 54, type: 'web', name: '苯酚溶液', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 55, type: 'web', name: '过氧化二苯甲酰', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"},
    {id: 56, type: 'web', name: '醋酸乙酯', r: 15, color: 'rgb(255 48 48)', cover:"http://zstp.nrcc.com.cn/static/img/chemistryHover.png"}, 
    {id: 1002, type: 'web', name: '紫荆花涂料（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 1003, type: 'web', name: '上海富柏化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 1004, type: 'web', name: '上海雪垠化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 1005, type: 'web', name: '上海立得催化剂有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 1006, type: 'web', name: '上海东大化学有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 1007, type: 'web', name: '美坚化工（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 1008, type: 'web', name: '上海抚佳精细化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 1009, type: 'web', name: '上海台界化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10010, type: 'web', name: '上海依田化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10011, type: 'web', name: '上海友豪科技股份有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10012, type: 'web', name: '中远关西涂料（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10013, type: 'web', name: '上海金狮化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10014, type: 'web', name: '上海未来企业股份有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10015, type: 'web', name: '上海荟百精细化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10016, type: 'web', name: '科莱恩催化剂（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10017, type: 'web', name: '上海欣旭化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10018, type: 'web', name: '美凯威奇（上海）新材料科技有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10019, type: 'web', name: '圣莱科特精细化工（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10020, type: 'web', name: '国药集团化学试剂上海有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10021, type: 'web', name: '中国科学院上海有机化学研究所（金山基地）', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10022, type: 'web', name: '华界化学（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10023, type: 'web', name: '上海甘田光学材料有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10024, type: 'web', name: '上海赫腾精细化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10025, type: 'web', name: '花王（上海）化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10026, type: 'web', name: '上海群力化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10027, type: 'web', name: '上海豪胜化工科技有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10028, type: 'web', name: '上海共拓医药化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10029, type: 'web', name: '上海合全药业股份有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10030, type: 'web', name: '上海巴德士化工新材料有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10031, type: 'web', name: '上海乘鹰新材料有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10032, type: 'web', name: '上海华谊集团华原化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10033, type: 'web', name: '上海强盛化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10034, type: 'web', name: '上海零星危险化学品物流有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10035, type: 'web', name: '立邦涂料（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10036, type: 'web', name: '中天科盛（上海）企业发展股份有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10037, type: 'web', name: '上海晶扬国际物流有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10038, type: 'web', name: '东曹（上海）聚氨酯有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10039, type: 'web', name: '上海欧亚合成材料股份有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10040, type: 'web', name: '上海博荟化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10041, type: 'web', name: '上海试四化学品有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10042, type: 'web', name: '帕珂表面处理技术（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10043, type: 'web', name: '东邦化学（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10044, type: 'web', name: '上海小鸟油漆有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10045, type: 'web', name: '上海金山石化物流股份有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10046, type: 'web', name: '上海绘兰材料科技有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10047, type: 'web', name: '中轻日化科技有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10048, type: 'web', name: '上海北芳危险品物流有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10049, type: 'web', name: '上海安化生物技术有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10050, type: 'web', name: '上海邦高化学有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10051, type: 'web', name: '创兴精细化学（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10052, type: 'web', name: '上海津力生物科技股份有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10053, type: 'web', name: '上海联乐化工科技有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10054, type: 'web', name: '上海益威实业有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10055, type: 'web', name: '上海峰彩实业有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10056, type: 'web', name: '上海春宝化工有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10057, type: 'web', name: '上海海洲工贸有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10058, type: 'web', name: '永星化工（上海）有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"},
    {id: 10059, type: 'web', name: '上海汇得科技股份有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"}, 
    {id: 10060, type: 'web', name: '上海北芳储运集团有限公司', r: 15, color: 'rgb(255 228 120)', cover: "http://zstp.nrcc.com.cn/static/img/companyHover.png"}, 
  ],
  links: [
    {id: 1, source: 1002, type: '', target: 14},
    {id: 2, source: 1002, type: '', target: 40},
    {id: 3, source: 1003, type: '', target: 46},
    {id: 4, source: 1003, type: '', target: 43},
    {id: 5, source: 1004, type: '', target: 32},
    {id: 6, source: 1005, type: '', target: 19},
    {id: 7, source: 1006, type: '', target: 35},
    {id: 8, source: 1006, type: '', target: 34},
    {id: 9, source: 1007, type: '', target: 30},
    {id: 10, source: 1008, type: '', target: 33},
    {id: 11, source: 1008, type: '', target: 35},
    {id: 12, source: 1008, type: '', target: 2},
  ]
}